name: Deploy TimesheetDB Tables

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-schema:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy TimesheetDB schema (tables only)
        run: |
          sqlcmd -S localhost -d TimesheetDB -U "${{ secrets.SQL_USER }}" -P "${{ secrets.SQL_PASSWORD }}" -i database/SQLDatabaseCreation.sql
