name: Deploy SSIS Package and Run SQL Jobs Final

on:
  workflow_dispatch:

jobs:
  deploy-and-run:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set PowerShell Execution Policy
        shell: powershell
        run: |
          Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass

      - name: Debug Repository Contents
        shell: powershell
        run: |
          Get-ChildItem -Path "${{ github.workspace }}" -Recurse | Format-Table Name, Directory, Length, LastWriteTime

     
      - name: Create SSIS Folder
        shell: powershell
        run: |
          sqlcmd -S localhost -d SSISDB -E" `
          -Q "EXEC [catalog].[create_folder] @folder_name='MonitoringFolder'"

      - name: Deploy SSIS Package using SSISDeploy
        shell: powershell
        run: |
          & "C:\DevopTools\SSISDeploy.exe" `
            -sourcePath "C:\Repositories\sc_MehulPatel_2025\DatabaseAdministration\HandsOnProject\Timesheet\TimesheetProject.ispac" `
            -destinationServer "localhost" `
            -destinationPath "/SSISDB/MonitoringFolder/TimesheetProject" `
            -authenticationType "Windows" `
            2>&1 | Out-File -FilePath "ssisdeploy.log"
          if ($LASTEXITCODE -ne 0) { throw "SSISDeploy failed. See ssisdeploy.log for details." }
          Get-Content -Path "ssisdeploy.log"

      - name: Run SQL Agent Job - ClientTableJob
        shell: powershell
        run: |
          sqlcmd -S localhost -d msdb -U "${{ secrets.SQL_USER }}" -P "${{ secrets.SQL_PASSWORD }}" `
          -Q "EXEC msdb.dbo.sp_start_job @job_name='ClientTableJob'"

      - name: Run SQL Agent Job - EmployeeJob
        shell: powershell
        run: |
          sqlcmd -S localhost -d msdb -U "${{ secrets.SQL_USER }}" -P "${{ secrets.SQL_PASSWORD }}" `
          -Q "EXEC msdb.dbo.sp_start_job @job_name='EmployeeJob'"

      - name: Run SQL Agent Job - TimesheetJob
        shell: powershell
        run: |
          sqlcmd -S localhost -d msdb -U "${{ secrets.SQL_USER }}" -P "${{ secrets.SQL_PASSWORD }}" `
          -Q "EXEC msdb.dbo.sp_start_job @job_name='TimesheetJob'"

      - name: Run SQL Agent Job - LeaveTableJob
        shell: powershell
        run: |
          sqlcmd -S localhost -d msdb -U "${{ secrets.SQL_USER }}" -P "${{ secrets.SQL_PASSWORD }}" `
          -Q "EXEC msdb.dbo.sp_start_job @job_name='LeaveTableJob'"
 
