name: Deploy SSIS Package and Run SQL Jobs Final

on:
  workflow_dispatch:

jobs:
  deploy-and-run:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set PowerShell Execution Policy
        shell: powershell
        run: |
          Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
     
      - name: Create SSIS Folder
        shell: cmd
        run: |
          sqlcmd -S LAPTOP-VL9R9CSO -d SSISDB -E -Q "EXEC [catalog].[create_folder] @folder_name='TimesheetProject'"
      - name: Deploy SSIS Package using SSISDeploy
        shell: cmd
        run: |
            C:\DevopTools\SSISDeploy.exe -s:C:\Repositories\sc_MehulPatel_2025\DatabaseAdministration\HandsOnProject\Timesheet\TimesheetProject.ispac ^
            -d:CATALOG;/SSISDB/TimesheetProject/TimesheetProject;. ^
            -authType:WIN ^
 
